### PR TITLE
Should Fix #1

### LINKED ISSUE #1: Fix Slack request verification
# Description
We'd like to verify that requests come from Slack to ensure random requests are not fielded.

# Relevant files
- A current attempt is in [./src/utils/index.ts](./src/utils/index.ts) using the Worker runtime [SubtleCrypto](https://developers.cloudflare.com/workers/runtime-apis/web-crypto) library. `digest()` doesn't work because it doesn't use the key to hash.
- Another approach could use an npm library to handle the hashes rather than doing something manually. Note that for newcomers to TypeScript, a types library may also need to be imported.

### PR DESCRIPTION
**Pull request by Ace314159**
I think I've fixed #1. There were 2 things that I had to change.

One was that doing `request.body` didn't actually get the body, but instead returned some `ReadableStream` object. Using `text()` got what we wanted.

The second was that `slackSignature` wasn't converted to a `Uint8Array` properly. The old approach using a utf8 encoder, which was what we needed for the `sigBasestring`, but `slackSignature` should be interpreted as a string of consecutive hex numbers. I couldn't find a prebuilt function to do that without having to add the node types, so I just used a loop for the conversion.

However, although the verification seems to work, the actual shorten request always times out. I think it's just because my cf worker is misconfigured since this happens even if I comment out the verification part.

### CODE REVIEW

File: src/utils/index.ts [hunk 1]
```diff
@@ -28,15 +29,15 @@ export const validSlackRequest = async (request: Request): Promise<boolean> => {
...
-
 		if (version && slackSignature) {
-			const signatureUint8 = encoder.encode(slackSignature)
+			// Convert hex digest to Uint8Array
+			const signatureUint8 = new Uint8Array(slackSignature.length / 2);
+			for(let i = 0; i < slackSignature.length; i += 2) {
+				signatureUint8[i / 2] = parseInt(slackSignature.slice(i, i + 2), 16);
+			}
+
 			// We want to verify that hte slack signature matches what we hash with the key we made
```
Comment (aadibajpai) [inline src/utils/index.ts]:
```suggestion
			// We want to verify that the slack signature matches what we hash with the key we made
```
might as well

**Comment by gfting** [comment]
This looks good to me, what testing have you tried thus far?

**Review by gfting — COMMENTED** [review]
This looks good to me, what testing have you tried thus far?

**Comment by Ace314159** [comment]
Currently, I've only tried a request from Slack and one without any of the headers and both had the correct behavior. I should probably also try it with invalid signatures to make sure the signature is actually being verified. I was thinking of trying signatures with: a valid hex string, a valid hex string with the correct length, and an invalid hex string.

**Comment by Ace314159** [comment]
I've tested them all on my local machine and it all seems to work properly.

Also, I noticed that if the timestamp field does not exist, it essentially bypasses the replay attack check. The header field should exist in all requests from Slack, so should I change the code?

**Comment by gfting** [comment]
> I've tested them all on my local machine and it all seems to work properly.
> 
> Also, I noticed that if the timestamp field does not exist, it essentially bypasses the replay attack check. The header field should exist in all requests from Slack, so should I change the code?

Sure, that sounds fine to me.

**Comment by gfting** [comment]
Looks great, thank you!
